- hosts: rocky
  become: yes
  vars_files:
    - ./vars.yml
  tasks:
    - name: Install_calibre.yml
      import_tasks: ./playbooks/install_calibre.yml
    - name: calibre_setup.yml
      import_tasks: ./playbooks/calibre_setup.yml
