- name: copy config file
  ansible.builtin.copy:
    src: ../global.py.json
    dest: /home/{{user}}/.config/calibre/global.py.json

# - name: copy server config
#   ansible.builtin.copy:
#     src: ../server-config.txt
#     dest: /home/{{user}}/.config/calibre/server-config.txt
 
# - name: copy dynamic pickle
#   ansible.builtin.copy:
#     src: ../dynamic.pickle.json
#     dest: /home/{{user}}/.config/calibre/dynamic.pickle.json

# - name: Replace content_server_ssl_certificate path in file
#   ansible.builtin.replace:
#     path: /home/{{user}}/.config/calibre/dynamic.pickle.json
#     regexp: '"choose_path_srv_opts_ssl_certfile": ".*"'
#     replace: '"choose_path_srv_opts_ssl_certfile": "/etc/pki/tls/certs"'

# - name: Replace content_server_ssl_key path in file
#   ansible.builtin.replace:
#     path: /home/{{user}}/.config/calibre/dynamic.pickle.json
#     regexp: '"choose_path_srv_opts_ssl_keyfile": ".*"'
#     replace: '"choose_path_srv_opts_ssl_keyfile": "{{ content_server_ssl_key_dir }}"'

# - name: Replace content_server_ssl_certificate in file
#   ansible.builtin.replace:
#     path: /home/{{user}}/.config/calibre/server-config.txt
#     regexp: 'ssl_certfile'
#     replace: 'ssl_certfile /etc/pki/tls/certs/content_server.crt'

# - name: Replace content_server_ssl_key in file
#   ansible.builtin.replace:
#     path: /home/{{user}}/.config/calibre/server-config.txt
#     regexp: 'ssl_keyfile'
#     replace: 'ssl_keyfile {{ content_server_ssl_key_dir }}/content_server.key'

- name: Replace database_path in file
  ansible.builtin.replace:
     path: /home/{{user}}/.config/calibre/global.py.json
     regexp: '"database_path": ".*"'
     replace: '"database_path": "/home/{{user}}/library1.db"'

- name: Replace library_path in file
  ansible.builtin.replace:
     path: /home/{{user}}/.config/calibre/global.py.json
     regexp: '"library_path": ".*"'
     replace: '"library_path": "/home/{{user}}/Calibre Library"'


