- name: Update packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Install dependencies for calibre
  ansible.builtin.package:
    name:
      - python
      - xdg-utils
      - xz
      - lzma
      - mesa-libGL
      - freeglut
      - freeglut-devel
      - epel-release
      - curl
    state: present

- name: Install xcb-util-cursor
  ansible.builtin.package:
    name:
      - xcb-util-cursor
    state: present

- name: Download calibre installer script
  ansible.builtin.uri:
    url: https://download.calibre-ebook.com/linux-installer.sh
    dest: /tmp/linux-installer.sh
    return_content: yes

- name: Run calibre installer script
  command: sh /tmp/linux-installer.sh
  args:
    creates: /usr/bin/calibre
