- name: Install cryptography library
  package:
    name: python3-cryptography
    state: present
 
- name: Generate a private key
  community.crypto.openssl_privatekey:
    path: "/etc/nginx/conf.d/content_server.key"
    state: present
    force: yes

- name: Create a CSR (Certificate Signing Request)
  community.crypto.openssl_csr:
    path: "/etc/nginx/conf.d/content_server.csr"
    state: present
    subject: "{{ content_server_subject }}"
    privatekey_path: "/etc/nginx/conf.d/content_server.key"


- name: Generate the self-signed certificate
  community.crypto.x509_certificate:
    path: "/etc/nginx/conf.d/content_server.crt"
    state: present
    subject: "{{ content_server_subject }}"
    provider: selfsigned
    csr_path: "/etc/nginx/conf.d/content_server.csr"
    privatekey_path: "/etc/nginx/conf.d/content_server.key"


